<?php

namespace cjohnson\ContentManagementSystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRowRepository extends EntityRepository
{
    /**
     * @param Page $page
     *
     * @return array
     */
    public function findAllByPageRankOrder(Page $page)
    {
        return $this->getEntityManager()->createQuery("SELECT p FROM
                                                        cjohnsonContentManagementSystemBundle:PageRow p
                                                        where p.page=:page
                                                        order by p.rank")
            ->setParameter('page', $page)
            ->getResult();
    }
}
