<?php

namespace cjohnson\ContentManagementSystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RowComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RowComponentRepository extends EntityRepository
{
    public function findAllByRowRankOrder(Row $row)
    {
        return $this->getEntityManager()->createQuery("SELECT rc FROM
                                                        cjohnsonContentManagementSystemBundle:RowComponent rc
                                                        where rc.row=:row
                                                        order by rc.rank")
            ->setParameter('row', $row)
            ->getResult();
    }
}
