<?php

namespace cjohnson\ContentManagementSystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RowRepository extends EntityRepository
{
}
